# Settings for the app
app:
  # HTML Title
  title: Georgetown Open Space
  # Header name
  name: "Georgetown Open Space"
  # Meta description that will show up in Google search results
  meta_description: "_(Welcome! We are a community of residents and stakeholders who are monitoring the cleanup of toxic waste in Seattle's Duwamish River.)"
  # Meta author that will show up in Google search results
  meta_author: SmarterCleanup.org

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

map:
# Settings for map and layer configs
  geolocation_enabled: true
  geolocation_onload: false
  cartodb_enabled: true
  #  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [46.500, -124, 48.5, -119] # south, west, north, east

  options:
    center:
      lat: 47.54403
      lng: -122.31890
    zoom: 15
    minZoom: 1
    maxZoom: 18
  layers:
    # SmarterCleanup Mapbox base layer:
    - id: osm
      type: basemap
      defaultBase: true
      url: //api.tiles.mapbox.com/v4/smartercleanup.k9dcl2i9/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: satellite
      type: basemap
      url: //api.tiles.mapbox.com/v4/smartercleanup.pe3o4gdn/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    # Carto basemap additions layer
    - id: additions
      url: https://smartercleanup.cartodb.com/api/v2/viz/3c0197f8-c7d8-11e5-8232-0ecfd53eb7d3/viz.json
      type: cartodb

  # Legend Layers

    - id: restoration
      url: https://k7b7dyc4v3.execute-api.us-west-2.amazonaws.com/production/getLandmarks
      type: landmark
      sources:
        - "http://a.tiles.mapbox.com/v4/smartercleanup.k9dcl2i9/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw"

    - id: gtopenspace
      type: place
      slug: idea

       # WRIA9 watershed
    - id: watershed
      type: cartodb
      url: "https://heyduwamishcore.cartodb.com/api/v2/viz/61226fec-0399-11e6-8de1-0e31c9be1b51/viz.json"

    - id: cleanup
      type: cartodb
      url: "https://smartercleanup.cartodb.com/api/v2/viz/b369d508-c02b-11e5-9a08-0ecfd53eb7d3/viz.json"

      # Land Use
    - id: landuse
      type: cartodb
      url: "https://hdbig.cartodb.com/api/v2/viz/76d1e054-d5ed-11e5-bf91-0e5db1731f59/viz.json"
      opacity: 0.5

      # Green Seattle Partnership restoration phases
    - id: phases
      type: cartodb
      url: "https://gis206.cartodb.com/api/v2/viz/217a2e02-e729-11e5-9bd4-0e5db1731f59/viz.json"

      # WMS Original Flow
    - id: duwamish-original
      url: https://smartercleanup.cartodb.com/api/v2/viz/ab34ca50-c6fc-11e5-ba65-0ecd1babdde5/viz.json
      type: cartodb
      opacity: 0.4

      # Noxious Weeds
    - id: noxious-weeds
      type: cartodb
      url: "https://hdbig.cartodb.com/api/v2/viz/f9350ac8-d677-11e5-980b-0e5db1731f59/viz.json"
      opacity: 0.5

# The keys show up in the dropdown list when you are adding a new place

# The values map the place type to map icons (defined below).
place_types:

  mapboxZoomStyle:
    - condition: '{{layer.focused}} === true'
      icon:
        iconSize: [50, 50]
        iconAnchor: [25, 25]
    - condition: '{{map.zoom}} < 16'
      icon:
        iconSize: [20, 20]
        iconAnchor: [10, 10]
    - condition: '{{map.zoom}} >= 16'
      icon:
        iconSize: [30, 30]
        iconAnchor: [15, 15]



  mapbox:
    # Mapbox Points
    rules:
    # LineString
      - condition: '"{{geometry.type}}" == "LineString"'
        style:
          color: "{{properties.stroke}}"
          opacity: '{{properties.stroke-opacity}}'
          weight: "{{properties.stroke-width}}"
    # Polygons
      - condition: '"{{geometry.type}}" == "Polygon"'
        style:
          shapeType: polygon
          fillColor: "{{properties.fill}}"
          fill: 'true'
          color: "{{properties.stroke}}"
          opacity: 0.7
          fillOpacity: '{{properties.fill-opacity}}'
          weight: "{{properties.stroke-width}}"




  low:
    label: _(Low)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-a5cf32.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-f95016.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-a5cf32.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: '{{map.zoom}} >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-a5cf32.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]
  medium:
    label: _(Medium)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-f39914.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-f95016.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-f39914.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: '{{map.zoom}} >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-f39914.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]
  high:
    label: _(High)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-e1264d.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-f95016.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-e1264d.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: '{{map.zoom}} >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-e1264d.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]
  streetscape:
    label: _(Streetscape)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [60, 60]
          iconAnchor: [30, 30]
          shadowSize: [60, 60]
          shadowAnchor: [30, 30]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [12, 12]
          iconAnchor: [6, 6]

      - condition: '{{map.zoom}} < 15'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]

      - condition: '{{map.zoom}} >= 15'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [30, 30]
          iconAnchor: [15, 15]

  park-improvement:
    label: _(Park Improvement)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-star-green.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [60, 60]
          iconAnchor: [30, 30]
          shadowSize: [60, 60]
          shadowAnchor: [30, 30]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/marker-star-green.png
          iconSize: [12, 12]
          iconAnchor: [6, 6]

      - condition: '{{map.zoom}} < 15'
        icon:
          iconUrl: /static/css/images/markers/marker-star-green.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]

      - condition: '{{map.zoom}} >= 15'
        icon:
          iconUrl: /static/css/images/markers/marker-star-green.png
          iconSize: [30, 30]
          iconAnchor: [15, 15]

# Sidebar and activity stream should be enabled and disabled together!
# note: sidebar is aka 'MasterLegend'
# TODO: Couple the sidebar and activity stream because the activity stream is a component of the sidebar
sidebar:
  enabled: true
  legend_enabled: true
  slug: filter-type
  # Layers are defined in the "map config" section
  # A panel's icon is a icon's name taken from here:
  # https://fortawesome.github.io/Font-Awesome/icons/
  panels:
    - id: gis-layers
      icon: list
      view: GISLegendView
      title: _(Map Layers:)
      basemaps:
        - id: osm
          title: _(OpenStreetMap)
          visibleDefault: true
        - id: satellite
          title: _(Satellite View)
          visibleDefault: false
      groupings:
        - id: grp-community
          title: _(Select All)
          visibleDefault: true
          layers:
            - id: gtopenspace
              title: _(Community Reports)
              visibleDefault: true

            - id: cleanup
              title: _(River Cleanup Plan)
              visibleDefault: false

            - id: restoration
              title: _(Restoration Sites)
              visibleDefault: false

        - id: grp-land
          title: _(Land Data)
          visibleDefault: false
          layers:
              # Land Use
            - id: landuse
              title: _(Land use)
              visibleDefault: false

              # Green Seattle Partnership restoration phases
            - id: phases
              title: _(Green Seattle partnership)
              visibleDefault: false

              # Noxious Weeds
            - id: noxious-weeds
              title: _(Noxious Weeds)
              visibleDefault: false

              # WRIA9 watershed
            - id: watershed
              title: _(Watershed)
              visibleDefault: false

        - id: grp-history
          title: _(Historical Data)
          visibleDefault: false
          layers:

              # WMS Original Flow
            - id: duwamish-original
              title: _(Original River Path)
              visibleDefault: false

    - id: ticker
      view: ActivityView
      icon: comments-o
      activity: true
      title: _(Activity Stream:)

    - id: reports_legend
      title: _(Citizen Reports:)
      view: LegendView
      icon: info-circle
      items:
        - title: _(Observations)
          image: /static/css/images/markers/marker-observation.png
          url: /filter/observation
        - title: _(Ideas)
          image: /static/css/images/markers/marker-idea.png
          url: /filter/idea
        - title: _(Questions)
          image: /static/css/images/markers/marker-question.png
          url: /filter/question
        - title: _(Complaints)
          image: /static/css/images/markers/marker-complaint.png
          url: /filter/complaint

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  dataset_slug: report # default is 'place'
  adding_supported: false
  add_button_label: _(Share an idea on the map!)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Show list of ideas)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Put it on the map!)

  location_item_name: location


  #### begin dynamic form config ####
  #TODO: maybe add an autocomplete
  place_detail:
    high:
      includeOnForm: true
      name: location_type
      dataset: gtopenspace
      icon_url: /static/css/images/markers/marker-e1264d.png
      value: high
      label: _(High priority)
      fields:
        - name: title
          type: text
          prompt: _(Title:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: true
        - name: comment
          type: textarea
          prompt: _(Comment:)
          display_prompt:
          placeholder: _(Enter comment...)
          optional: true
    medium:
      includeOnForm: true
      name: location_type
      dataset: gtopenspace
      icon_url: /static/css/images/markers/marker-f39914.png
      value: medium
      label: _(Medium priority)
      fields:
        - name: title
          type: text
          prompt: _(Title:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: true
        - name: comment
          type: textarea
          prompt: _(Comment:)
          display_prompt:
          placeholder: _(Enter comment...)
          optional: true
    low:
      includeOnForm: true
      name: location_type
      dataset: gtopenspace
      icon_url: /static/css/images/markers/marker-a5cf32.png
      value: low
      label: _(Low priority)
      fields:
        - name: title
          type: text
          prompt: _(Title:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: true
        - name: comment
          type: textarea
          prompt: _(Comment:)
          display_prompt:
          placeholder: _(Enter comment...)
          optional: true
    streetscape:
      includeOnForm: false     
      name: location_type
      dataset: gtopenspace
      icon_url: /static/css/images/markers/marker-star.png
      value: streetscape
      label: _(Streetscape)
      fields:
        - name: title
          type: text
          prompt: _(Title:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: true
        - name: comment
          type: textarea
          prompt: _(Comment:)
          display_prompt:
          placeholder: _(Enter comment...)
          optional: true
    park-improvement:
      includeOnForm: false     
      name: location_type
      dataset: gtopenspace
      icon_url: /static/css/images/markers/marker-star.png
      value: park-improvement
      label: _(Park improvement)
      fields:
        - name: title
          type: text
          prompt: _(Title:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: true
        - name: comment
          type: textarea
          prompt: _(Comment:)
          display_prompt:
          placeholder: _(Enter comment...)
          optional: true

  # define form elements that appear on every form here
  common_form_elements:
    # - name: submitter_name
    #   type: text
    #   prompt: _(Your name)
    #   placeholder: _(Name)
    #   optional: true
    # - name: private-submitter_email
    #   type: text
    #   prompt: _(Your Email)
    #   optional: true
    #   sticky: true
    #   attrs:
    #     - key: placeholder
    #       value: _(Receive email updates on your report)
    #     - key: size
    #       value: 30
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - type: submit
      label: _(Put it on the map!)

  #### end dynamic form config ####

## Can we delete this?

  items:
    - prompt: _(Type of report)
      type: select
      options:
        - label: _(Observation)
          value: observation
        - label: _(Question)
          value: question
        - label: _(Idea)
          value: idea
        - label: _(Complaint)
          value: complaint
      name: location_type
      attrs:
        - key: required
    - prompt: _(Title of report)
      type: text
      name: name
      optional:
      attrs:
        - key: required
        - key: placeholder
          value: _(Enter title)
        - key: size
          value: 30
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Receive email updates on your report)
        - key: size
          value: 30
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    hide_from_top_bar: true

story:
  streetscapes:
      tagline: _(Explore other priority sites)
      order: 
        - idea/628
        - idea/629
        - idea/634
        - idea/631
        - idea/635
        - idea/633
        - idea/636
        - idea/637
        - idea/552
        - idea/638
        - idea/639
        - idea/643
        - idea/641
        - idea/642
        - idea/644
        - idea/645
        - idea/646
        - idea/647
        - idea/648
        - idea/649
        - idea/650
        - idea/651
        - idea/649
        - idea/650
        - idea/651
        - idea/558
        - idea/559
        - idea/560
        - idea/564
        - idea/572
        - idea/573
        - idea/594
        - idea/595
        - idea/574
        - idea/575
        - idea/576
        - idea/580
        - idea/585
        - idea/586
  test_story2:
      tagline: _(This is a priority site. Use arrows to explore others)
      order: 
        - friends-of-georgetown-history-museum
        - ruby-chow-park
        - georgetown-steam-plant
