# Settings for the app
app:
  # HTML Title
  title: Our Lake Washington
  # Header name
  name: Our Lake Washington
  # Meta description that will show up in Google search results
  meta_description: _(We are looking out to keep Lake Washington healthy for all)
  # Meta author that will show up in Google search results
  meta_author: smartercleanup.org


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  cartodb_enabled: true

  geocoding_enabled: false
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  options:
    center:
      lat: 47.75121
      lng: -122.25882
    zoom: 15
    minZoom: 1
    maxZoom: 18
  layers:
    # Mapbox Satellite
    - url: //api.tiles.mapbox.com/v4/lakewashington.p9ccgp63/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibGFrZXdhc2hpbmd0b24iLCJhIjoiY2lsNnhjdGhzMDZ4ZnUybHpvbzN0Y2dobiJ9.7e88oaSsl-d0ZQYD_5in9w
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: areas-of-interest
      url: https://k7b7dyc4v3.execute-api.us-west-2.amazonaws.com/production/mapbox/landmarks?url=https://a.tiles.mapbox.com/v4/lakewashington.p9ccgp63/features.json?access_token=pk.eyJ1IjoibGFrZXdhc2hpbmd0b24iLCJhIjoiY2lsNnhjdGhzMDZ4ZnUybHpvbzN0Y2dobiJ9.7e88oaSsl-d0ZQYD_5in9w
      type: landmark
      visibleDefault: true

      # Kenmore Land use
    - id: kenmore-land-use
      type: cartodb
      url: https://smartercleanup.cartodb.com/api/v2/viz/7eed0a34-dddb-11e5-9c46-0e787de82d45/viz.json

      # Noxious Weeds
    - id: noxious-weeds
      type: cartodb
      url: "https://hdbig.cartodb.com/api/v2/viz/f9350ac8-d677-11e5-980b-0e5db1731f59/viz.json"

      # Eco Regions
    - id: eco-regions
      type: cartodb
      url: "https://smartercleanup.cartodb.com/api/v2/viz/9d4d8cfa-ddc3-11e5-9bed-0ea31932ec1d/viz.json"

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  observation:
    label: _(Observation)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 14'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [12, 14.5]
          iconAnchor: [6, 14.5]

      - condition: '{{map.zoom}} >= 14'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  question:
    label: _(Question)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-dbcf2c.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 14'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [12, 14.5]
          iconAnchor: [6, 14.5]

      - condition: '{{map.zoom}} >= 14'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  idea:
    label: _(Idea)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-f95016.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 14'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [12, 14.5]
          iconAnchor: [6, 14.5]

      - condition: '{{map.zoom}} >= 14'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  complaint:
    label: _(Complaint)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 14'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [12, 14.5]
          iconAnchor: [6, 14.5]

      - condition: '{{map.zoom}} >= 14'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  mapbox:
    # Mapbox Points
    rules:
    # LineString
      - condition: '"{{geometry.type}}" == "LineString"'
        style:
          color: "{{properties.stroke}}"
          opacity: '{{properties.stroke-opacity}}'
          weight: "{{properties.stroke-width}}"
    # Polygons
      - condition: '"{{geometry.type}}" == "Polygon"'
        style:
          shapeType: polygon
          fillColor: "{{properties.fill}}"
          fill: 'true'
          color: "{{properties.stroke}}"
          opacity: 0.7
          fillOpacity: '{{properties.fill-opacity}}'
          weight: "{{properties.stroke-width}}"

      - condition: '"{{geometry.type}}" == "Point"'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [30, 30]
          iconAnchor: [15, 15]

      - condition: '"{{geometry.type}}" == "Point" && "{{layer.focused}}" === true'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

sidebar:
  enabled: true
  legend_enabled: true
  slug: filter-type
  # Layers are defined in the "map config" section
  # TODO: Refactor the Layers section into its own sidebar
  panels:
    legend:
      title: _(Legend:)
      items:
        - title: _(Observations)
          image: /static/css/images/markers/marker-observation.png
          url: /filter/observation
        - title: _(Ideas)
          image: /static/css/images/markers/marker-idea.png
          url: /filter/idea
        - title: _(Questions)
          image: /static/css/images/markers/marker-question.png
          url: /filter/question
        - title: _(Complaints)
          image: /static/css/images/markers/marker-complaint.png
          url: /filter/complaint
    gis_layers:
      title: _(Map Layers:)
      groupings:
        - id: grp-land
          title: _(Land Data)
          visibleDefault: false
          layers:
              # Ares of interst
            - id: areas-of-interest
              title: _(Areas of interest)
              description: _(Areas of interest)
              visibleDefault: true

              # Noxious Weeds
            - id: noxious-weeds
              title: _(Noxious Weeds)
              description: _(Invasive species of weeds)
              visibleDefault: false

              # Eco Regions
            - id: eco-regions
              title: _(Eco Regions)
              description: _(Eco regions of Washington State)
              visibleDefault: false

              # Kenmore Land use
            - id: kenmore-land-use
              title: _(Kenmore land use)
              description: _(Land use data for Kenmore)
              visibleDefault: false

    ticker:
      title: _(Activity Stream:)

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Put a comment on the map!)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(See all comments)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(Type of report)
      type: select
      options:
        - label: _(Observation)
          value: observation
        - label: _(Question)
          value: question
        - label: _(Idea)
          value: idea
        - label: _(Complaint)
          value: complaint
      name: location_type
      attrs:
        - key: required
    - prompt: _(Title of report)
      type: text
      name: name
      optional:
      attrs:
        - key: required
        - key: placeholder
          value: _(Enter title)
        - key: size
          value: 30
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Receive email updates on your report)
        - key: size
          value: 30
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: false

  - title: _(Get involved)
    slug: getinvolved
    name: contribute

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
